name: Marketcraft
version: ${project.version}
main: com.kitdacatsun.marketcraft.MarketCraft
api-version: 1.16

commands:
  shop:
    description: Opens the shop
    usage: /shop

  pay:
    description: A command for op's to give player curency
    usage: /pay <player> <amount>

  balance:
    description: A commmand to cheak player balance
    useage: /balance
    aliases: bal
    permission: balance

  bank:
    description: Used to spawn the bank villager
    usage: /bank

  playerShop:
    description: A command to add an item to the player shop
    usage: /playerShop

permissions:
  balance:
    description: Allows all players to cheak their balance
    default: true

