name: Marketcraft
version: ${project.version}
main: com.kitdacatsun.marketcraft.MarketCraft
api-version: 1.16

commands:
  price:
    description: Gets the prices of all items or a specific item
    usage: /price <all/item>
    aliases: price all

  shop:
    description: Opens the shop
    usage: /shop

  pay:
    description: A command for op's to give player curency
    usage: /pay <player> <amount>

  balance:
    description: A commmand to check player balance
    useage: /balance
    aliases: bal
    permission: balance

  villager:
    description: Used to spawn the villagers for the GUI interface
    usage: /villager <name>

  playerShop:
    description: A command to add an item to the player shop
    usage: /playerShop

permissions:
  balance:
    description: Allows all players to check their balance
    default: true

